# Generated by Django 5.0.1 on 2024-02-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followrs_posts_like_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coments',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='like',
            name='unlikes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='static/network/uploud/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
