# Generated by Django 5.0.1 on 2024-02-16 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_timestamp_like_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentAdd', to='network.coments')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeAdd', to='network.like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostDdd', to='network.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserADDPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
