# Generated by Django 5.0.1 on 2024-02-17 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_allpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r_comment', to='network.coments'),
            preserve_default=False,
        ),
    ]
