# Generated by Django 5.0.1 on 2024-02-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.DeleteModel(
            name='AllPost',
        ),
    ]
